networks:
  tadjiflix-api_network:
  tadjiflix-traefik_network:
    name: tadjiflix-traefik_network

volumes:
  mysql-data:
  traefik-data:

services:
  traefik:
    image: traefik:v2.10
    container_name: tadjiflix-traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "9080:80"      # HTTP - port atypique 9080 au lieu de 80
      - "9443:443"     # HTTPS - port atypique 9443 au lieu de 443
      - "9082:8080"    # Dashboard - port atypique 9082 au lieu de 8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config/traefik.yml:/traefik.yml:ro
      - ./traefik/config/config.yml:/config.yml:ro
      - traefik-data:/letsencrypt
    networks:
      - tadjiflix-traefik_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=tadjiflix-traefik_network
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik-tadjiflix.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.entrypoints=websecure
      - traefik.http.routers.traefik-dashboard.tls.certresolver=tadjiflix-tls
      - traefik.http.routers.traefik-dashboard.middlewares=traefik-auth@docker
      - traefik.http.middlewares.traefik-auth.basicauth.users=${BASIC_AUTH_TRAEFIC}

  tadjiflix-api_app:
    container_name: tadjiflix-api_app
    build:
      context: .
      dockerfile: ./infrastructure/php/Dockerfile
    networks:
      - tadjiflix-api_network
    volumes:
      - .:/var/task
      - ./var:/var/task/var        # force create ./var
      - ./vendor:/var/task/vendor  # force create ./vendor
    depends_on:
      - mysql

  nginx:
    image: nginx:1.23.4-alpine
    volumes:
      - .:/var/task
      - ./infrastructure/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tadjiflix-api_app
    networks:
      - tadjiflix-api_network
      - tadjiflix-traefik_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=tadjiflix-traefik_network

      - traefik.http.routers.symfony-ui.rule=Host(`${SYMFONY_SUBDOMAIN}.${DOMAIN_NAME}`) && !PathPrefix(`/api`)
      - traefik.http.routers.symfony-ui.tls=true
      - traefik.http.routers.symfony-ui.entrypoints=websecure
      - traefik.http.routers.symfony-ui.tls.certresolver=tadjiflix-tls
      - traefik.http.routers.symfony-ui.middlewares=symfony-auth@docker

      - traefik.http.routers.symfony-api.rule=Host(`${SYMFONY_SUBDOMAIN}.${DOMAIN_NAME}`) && PathPrefix(`/api`)
      - traefik.http.routers.symfony-api.tls=true
      - traefik.http.routers.symfony-api.entrypoints=websecure
      - traefik.http.routers.symfony-api.tls.certresolver=tadjiflix-tls

      # Authentification middleware
      - traefik.http.middlewares.symfony-auth.basicauth.users=${BASIC_AUTH_TRAEFIC}
      - traefik.http.services.symfony.loadbalancer.server.port=80

  mysql:
    image: bitnami/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '33271:3306'
    expose:
      - '3306'
    volumes:
      - type: volume
        source: mysql-data
        target: /bitnami/mysql/data
    networks:
      - tadjiflix-api_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "10253:1025"  # SMTP port
      - "18025:8025"  # Web Interface
    networks:
      - tadjiflix-api_network
      - tadjiflix-traefik_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=tadjiflix-traefik_network

      - traefik.http.routers.mailhog.rule=Host(`${MAILHOG_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.mailhog.tls=true
      - traefik.http.routers.mailhog.entrypoints=websecure
      - traefik.http.routers.mailhog.tls.certresolver=tadjiflix-tls
      - traefik.http.routers.mailhog.middlewares=symfony-auth@docker

      - traefik.http.services.mailhog.loadbalancer.server.port=8025

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    ports:
      - '8969:8080'
      - '8970:8443'
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - mysql
    networks:
      - tadjiflix-api_network
      - tadjiflix-traefik_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=tadjiflix-traefik_network

      - traefik.http.routers.phpmyadmin.rule=Host(`${PHPMYADMIN_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.routers.phpmyadmin.entrypoints=websecure
      - traefik.http.routers.phpmyadmin.tls.certresolver=tadjiflix-tls
      - traefik.http.routers.phpmyadmin.middlewares=symfony-auth@docker

      - traefik.http.services.phpmyadmin.loadbalancer.server.port=8080