# config.yml - Configuration dynamique pour Traefik
http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        # Désactivé la redirection SSL automatique
        # sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
          - "127.0.0.1/32"
          - "::1/128"

    gzip-compress:
      compress: {}

    # Ajout d'un middleware pour rediriger HTTP vers HTTPS sauf pour les challenges ACME
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
        priority: 100

  # Ajout d'une règle pour laisser passer les challenges ACME
  routers:
    acme-challenge:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      service: noop
      entryPoints:
        - web
      priority: 1000

  services:
    # Service factice pour la règle acme-challenge
    noop:
      loadBalancer:
        servers:
          - url: "http://localhost:9080"