# config.yml - Configuration dynamique pour Traefik
http:
  middlewares:
    # Middleware pour contourner l'authentification pour les challenges ACME
    acme-middleware:
      stripPrefix:
        prefixes:
          - "/.well-known/acme-challenge/"
        forceSlash: false

    default-headers:
      headers:
        frameDeny: true
        # Désactivé la redirection SSL automatique pour permettre les challenges ACME
        # sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
          - "127.0.0.1/32"
          - "::1/128"

    gzip-compress:
      compress: {}

  # Router global pour les challenges ACME (priorité élevée)
  routers:
    acme-global:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      service: acme-service
      entryPoints:
        - web
      priority: 999999  # Priorité très élevée

  # Service factice pour servir les challenges ACME
  services:
    acme-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"