# traefik.yml
api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
    # Commenté la redirection automatique pour permettre les challenges ACME
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: tadjiflix-tls

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: tadjiflix-traefik_network

  file:
    filename: /config.yml
    watch: true

certificatesResolvers:
  tadjiflix-tls:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}