# traefik.yml avec logging amélioré
api:
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
    # Commenté la redirection pour le debugging
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: tadjiflix-tls
    # Augmenter les timeouts
    transport:
      respondingTimeouts:
        readTimeout: 300s
        writeTimeout: 300s
        idleTimeout: 300s

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: tadjiflix-traefik_network
    # Augmenter le polling pour voir les changements rapidement
    swarmMode: false
    defaultRule: "Host(`{{ normalize .Name }}.${DOMAIN_NAME}`)"

  file:
    filename: /config.yml
    watch: true

certificatesResolvers:
  tadjiflix-tls:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# Augmenter le niveau de log pour le debugging
log:
  level: DEBUG
  format: json

# Activer et configurer les access logs
accessLog:
  format: json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-599"
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

# Activer le traçage pour mieux comprendre les problèmes
tracing:
  serviceName: tadjiflix-traefik
  spanNameLimit: 100